### ISSUE TITLE
提几点个人建议

### ISSUE THREAD

**Issue by easonjim** [smltq/spring-boot-demo#12]
1、spring boot版本问题，个人建议1.x，2.x，3.x
2、spring boot+cloud版本

**Comment by smltq** [comment]
1.目前2.1.x有一个单独开发分支的（可能不再更新及升级，有发现bug会修复)，以后会持续增加2.2.x，2.3.x，master的boot版本会尽量与官网一致
2.spring boot+cloud的话，尽量与官网当前版本保持一致，并修复发现的bug
3.需要其它开源框架示例的可以给我提issue

**Comment by smltq** [comment]
查看说明文档，目前不兼容的已独立分支，并只更新主干分支尽量与spring boot 官网版本同步
