### ISSUE TITLE
能添加mqtt demo嘛

### ISSUE THREAD

**Issue by zhuqiyun** [smltq/spring-boot-demo#13]

**Comment by smltq** [comment]
MQTT是协议吧，你需要哪个插件的demo：activemq、kafka、rabbitmq、zeromq、rocketmq的哪种，我只研究免费开源的插件哦，收费的demo不负责提供。

**Comment by smltq** [comment]
示例及文档已提交，具体查看源代码，该建议完成并关闭它。
