### ISSUE TITLE
Sign 项目bug

### ISSUE THREAD

**Issue by caidapao** [smltq/spring-boot-demo#17]
### 测试案例：
POST/PUT/DELETE 下，   如果在body 中使用  List<TestVo> 作为 controller 入参，即数组的JSON 格式，会解析失败

**Comment by caidapao** [comment]
- 不过这种可以通过接口文档的方式，强行让调用者使用{}的 JSON格式作为入参。
- 感谢作者的 Demo ，受益匪浅

**Comment by smltq** [comment]
你是指：com.easy.sign.controller.SignController控制器吗，testDelete有List支持示例哦。其它测试接口要支持的话，自行调下接口参数即可。

**Comment by caidapao** [comment]
> 

- 感谢作者的回复
- 完全明白你的意思，确实支持传 List 结构，但是最外层还是有个{}结构包着：{"list":[{},{},{}]}
- 但是我想表达的是： Spring 是支持直接传 list 而不需要{}包着的： [{},{},{}]。因此这种格式的参数传进来之后，会在这报错：com.easy.sign.utils.HttpUtil#getBodyParams line:40 parseObject 
- 所以当请求的 bodyParam 不是以 '{' 开头时，直接返回一个参数格式不正确可能是一个不错的选择。

---------

- Thank you for your time.
- I know exactly what you mean, it really supports list-type-request, but we still need to put list-type-request into a '{}' structure inside. 
- But what I just what to say is that spring has been always supporting list-type-request with no '{}' structure outside, so when a list-type-request comes in, it will throw Exceptions at com.easy.sign.utils.HttpUtil#getBodyParams line:40 parseObject.
- so when request bodyParam is not started with '{', just returning an IllegalParamType response maybe is a better way.

**Comment by caidapao** [comment]
> > 
> 
> * 感谢作者的回复
> * 完全明白你的意思，确实支持传 List 结构，但是最外层还是有个{}结构包着：{"list":[{},{},{}]}
> * 但是我想表达的是： Spring 是支持直接传 list 而不需要{}包着的： [{},{},{}]。因此这种格式的参数传进来之后，会在这报错：com.easy.sign.utils.HttpUtil#getBodyParams line:40 parseObject
> * 所以当请求的 bodyParam 不是以 '{' 开头时，直接返回一个参数格式不正确可能是一个不错的选择。
> 
> * Thank you for your time.
> * I know exactly what you mean, it really supports list-type-request, but we still need to put list-type-request into a '{}' structure inside.
> * But what I just what to say is that spring has been always supporting list-type-request with no '{}' structure outside, so when a list-type-request comes in, it will throw Exceptions at com.easy.sign.utils.HttpUtil#getBodyParams line:40 parseObject.
> * so when request bodyParam is not started with '{', just returning an IllegalParamType response maybe is a better way.

@smltq

**Comment by smltq** [comment]
谢谢你的反馈，已修复，增加数组参数签名支持。

示例接口地址：SignController.arrParamsTest
参数请求示例：
var settings = {
  "url": "http://localhost:8080/encoder/arrParamsTest",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "Sign": "6E06E2B2A830B03A74815D3DCCF6D2DC",
    "Timestamp": "1645412398",
    "Content-Type": "application/json"
  },
  "data": JSON.stringify([
    {
      "phone": "1111111111",
      "code": "11"
    },
    {
      "phone": "22222222222",
      "code": "22"
    },
    {
      "phone": "33333333333",
      "code": "33"
    },
    {
      "phone": "44444444444",
      "code": "44"
    }
  ]),
};

$.ajax(settings).done(function (response) {
  console.log(response);
});

**Comment by caidapao** [comment]
棒的咧！
