### ISSUE TITLE
cloud-alibaba  

### ISSUE THREAD

**Issue by a421492867** [smltq/spring-boot-demo#5]
dubbo整合nacos
服务提供者能够正常注册进去 并且dubbo也成功了
但是到了消费者，dubbo找不到服务提供者

会报No provider available 的错误

**Comment by smltq** [comment]
你是指ali-nacos-consumer-ribbon无法消费，还是ali-nacos-consumer-feign

**Comment by a421492867** [comment]
ali-nacos-dubbo-consumer

**Comment by smltq** [comment]
我试了下正确呢。
dubbo整合cloud是运行以下两个工程哦
- ali-nacos-dubbo-api：定义Dubbo服务接口工程
        
- ali-nacos-dubbo-provider：Dubbo服务提供方并向nacos注册服务，服务名：ali-nacos-dubbo-provider，端口：9001

- ali-nacos-dubbo-consumer：Dubbo服务消费方并向nacos注册服务，服务名：ali-nacos-dubbo-consumer，端口：9103
详细使用文档参考的使用示例章节：https://github.com/smltq/spring-boot-demo/blob/master/cloud-alibaba/README4.md
