### ISSUE TITLE
前端JS生成sign的问题

### ISSUE THREAD

**Issue by zc-zangchao** [smltq/spring-boot-demo#6]
您好，最近在做重放攻击相关的项目，
https://github.com/smltq/spring-boot-demo/blob/master/sign/HELP.md
看到这里面有相关的方案，有个疑问，
1、前端JS请求的Header里面包含sign，这个sign在前端如何生成呢？前端怎么保证密钥的安全呢？
2、如果此处只是代码示例，此方案只适合服务端的交互。由前端JS代码发起的请求，怎么安全的生成sign 或者 进行签名验证呢？

**Comment by smltq** [comment]
1.按与服务端约定的规则生成，前端不存秘钥
2.此方案也合适前后端交互，可以防篡改、防重放攻击。

**Comment by cuglaiyp** [comment]
约定规则，前端的规则也是能被看到的并不安全吧
