### ISSUE TITLE
多数据源

### ISSUE THREAD

**Issue by Strivema** [smltq/spring-boot-demo#7]
您好，多数据源配置的AOP读数据库的切点是不是写错了，

**Comment by smltq** [comment]
以贴上报错信息吗，方便我排查

**Comment by Strivema** [comment]
`package com.easy.mybatis.multidatasource.config;

import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.stereotype.Component;

@Aspect
@Component
public class DataSourceAop {
    @Pointcut("@annotation(com.easy.mybatis.multidatasource.annotation.Master) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.insert*(..)) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.add*(..)) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.update*(..)) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.edit*(..)) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.delete*(..)) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.remove*(..))")
    public void writePointcut() {

    }

    @Pointcut("!@annotation(com.easy.mybatis.multidatasource.annotation.Master) " +
            "&& (execution(* com.easy.mybatis.multidatasource.service..*.select*(..)) " +
            "|| execution(* com.easy.mybatis.multidatasource.service..*.get*(..)))")
    public void readPointcut() {

    }`
您看，readPointCut，里面的注解在代码22行，抱歉截屏不了

**Comment by smltq** [comment]
这个没有错的，你注意看下括号，类似这样(!master&&(select||get)。表示没有master注解并且是select或get开头的方法，去读库取数据。

**Comment by Strivema** [comment]
抱歉，没看见前面的非，不好意思
